<link rel="stylesheet" href="<?php echo $this->mediaUrl; ?>jquery/ui/css/smoothness/jquery-ui-1.8.7.custom.css" />
<link href="<?php echo $this->mediaUrl; ?>jquery/datatables/media/css/demo_page.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->mediaUrl; ?>jquery/datatables/media/css/demo_table_jui.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->mediaUrl; ?>jquery/datatables/media/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#moduleportallist').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "aoColumns": [null],
            "bStateSave": true
        });
    });

</script>

<a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showList")); ?>">zur&uuml;ck</a> &nbsp;&nbsp;

<h1><?php echo $this->entity->getValueByKey("modulename"); ?></h1>

<?php $portals = $this->entity->getValueByKey("portals"); ?>

<?php if (count($portals) > 0): ?>
    <table id="moduleportallist" class="table table-striped">
        <thead>
            <tr>
                <th>in folgenden Portalen vorhanden</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($portals as $portal): ?>
                <tr>
                    <td><a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showDetail", "id" => $portal["id"])); ?>"><?php echo $portal["name"]; ?></a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p> Dieses Modul ist aktuell in keinem Portal installiert.</p>
<?php endif; ?>
