<link rel="stylesheet" href="<?php echo $this->mediaUrl; ?>jquery/ui/css/smoothness/jquery-ui-1.8.7.custom.css" />
<link href="<?php echo $this->mediaUrl; ?>jquery/datatables/media/css/demo_page.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->mediaUrl; ?>jquery/datatables/media/css/demo_table_jui.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->mediaUrl; ?>jquery/datatables/media/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#pluginlist').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "aoColumns": [null, null],
            "bStateSave": true
        });
        $('#packagelist').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "aoColumns": [null, null],
            "bStateSave": true
        });
    });

</script>

<h1>Installierte Module</h1>    

<h3>Plugins</h3>

<?php if (count($this->collection) > 0): ?>
    <table id="pluginlist" class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Anzahl gefundener Installationen</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->collection["plugins"] as $plugin): ?>
                <tr>
                    <td><a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showModuleDetail", "id" => $plugin->getId())); ?>"><?php echo $plugin->getValueByKey("name"); ?></a></td>
                    <td><?php echo $plugin->getValueByKey("installs"); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p>keine Plugins vorhanden</p>
<?php endif; ?>
    
<h3>Packages</h3>

<?php if (count($this->collection) > 0): ?>
    <table id="packagelist" class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Anzahl gefundener Installationen</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->collection["packages"] as $package): ?>
                <tr>
                    <td><a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showModuleDetail", "id" => $package->getId())); ?>"><?php echo $package->getValueByKey("name"); ?></a></td>
                    <td><?php echo $package->getValueByKey("installs"); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p>keine Packages vorhanden</p>
<?php endif; ?>