<link rel="stylesheet" href="<?php echo $this->mediaUrl; ?>jquery/ui/css/smoothness/jquery-ui-1.8.7.custom.css" />
<link href="<?php echo $this->mediaUrl; ?>jquery/datatables/media/css/demo_page.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->mediaUrl; ?>jquery/datatables/media/css/demo_table_jui.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->mediaUrl; ?>jquery/datatables/media/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#portallist').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "aoColumns": [null, null, null, {"bSortable": false}, {"bSortable": false}],
            "bStateSave": true
        });
    });

</script>

<?php if($this->isAdmin): ?>
    <a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showAddForm")); ?>">neues Portal</a> &nbsp;&nbsp;
<?php endif; ?>
    
<h1>Portale</h1>

<?php if (count($this->collection) > 0): ?>
    <table id="portallist" class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Plugins</th>
                <th>Packages</th>
                <?php if($this->isAdmin): ?>
                    <th style="width: 50px;">&nbsp;</th>
                    <th style="width: 50px;">&nbsp;</th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->collection as $portal): ?>
                <tr>
                    <td><a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showDetail", "id" => $portal->getId())); ?>"><?php echo $portal->getValueByKey("name"); ?></a></td>
                    <td><?php echo $portal->getValueByKey("plugins"); ?></td>
                    <td><?php echo $portal->getValueByKey("packages"); ?></td>
                    <?php if($this->isAdmin): ?>
                        <td><a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showEditForm", "id" => $portal->getId())); ?>">edit</a></td>
                        <td><a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "deleteEntry", "id" => $portal->getId())); ?>" onclick="if(confirm(unescape('Diesen Eintrag wirklich l%F6schen ?'))){ return true;} return false;">delete</a></td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p>keine Portale vorhanden</p>
<?php endif; ?>