<link rel="stylesheet" href="<?php echo $this->mediaUrl; ?>jquery/ui/css/smoothness/jquery-ui-1.8.7.custom.css" />
<link href="<?php echo $this->mediaUrl; ?>jquery/datatables/media/css/demo_page.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->mediaUrl; ?>jquery/datatables/media/css/demo_table_jui.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->mediaUrl; ?>jquery/datatables/media/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#pluginlist').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "aoColumns": [null, null],
            "bStateSave": true
        });
        $('#packagelist').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "aoColumns": [null, null],
            "bStateSave": true
        });
        $('#statslist').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "aoColumns": [null, null],
            "bStateSave": true
        });
    });

</script>

<a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showList")); ?>">zur&uuml;ck</a> &nbsp;&nbsp;
<?php if ($this->isAdmin): ?>
    <a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showMd5CheckForm", "id" => $this->entity->getId())); ?>">Md5 Check</a> &nbsp;&nbsp;
    <a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "getSystemInfoFromPortal", "id" => $this->entity->getId())); ?>">Systeminformationen aktualisieren</a> &nbsp;&nbsp;
    <a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showEditForm", "id" => $this->entity->getId())); ?>">Portal bearbeiten</a>
<?php endif; ?>

<h1><?php echo $this->entity->getValueByKey("name"); ?></h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Name</td>
            <td><?php echo $this->entity->getValueByKey("name"); ?></td>
        </tr>
        <tr>
            <td>Server</td>
            <td><?php echo $this->entity->getValueByKey("server"); ?></td>
        </tr>
        <tr>
            <td>Pfad</td>
            <td><?php echo $this->entity->getValueByKey("path"); ?></td>
        </tr>
        <tr>
            <td>Url</td>
            <td><a href="<?php echo $this->entity->getValueByKey("url"); ?>" target="_blank"><?php echo $this->entity->getValueByKey("url"); ?></a></td>
        </tr>
        <tr>
            <td>Piwik Id</td>
            <td><?php echo $this->entity->getValueByKey("piwik_id"); ?> ( <?php echo $this->entity->getValueByKey("piwik_name") ?> ) 
                <?php if ($this->isAdmin): ?>
                    <?php $piwik_usage = $this->entity->getValueByKey("piwik_usage"); if (count($piwik_usage) > 0) : echo "Diese Piwik-Id wird ebenfalls bei folgenden Portalen verwendet: "; foreach($piwik_usage as $use):?><a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showEditForm", "id" => $use["id"])); ?>"><?php echo $use["name"]; ?></a>&nbsp;<?php endforeach; ?><?php endif;?>
                <?php else: ?>
                    <?php $piwik_usage = $this->entity->getValueByKey("piwik_usage"); if (count($piwik_usage) > 0) : echo "Diese Piwik-Id wird ebenfalls bei folgenden Portalen verwendet: "; foreach($piwik_usage as $use):?><b><?php echo $use["name"]; ?></b>&nbsp;<?php endforeach; ?><?php endif;?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>Plugins</td>
            <td><?php if($this->entity->getValueByKey("plugins") == ""){ echo "0"; } else { $pluginlist = $this->entity->getValueByKey("plugins"); echo count($pluginlist); } ?></td>
        </tr>
        <tr>
            <td>Packages</td>
            <td><?php if($this->entity->getValueByKey("packages") == ""){ echo "0"; } else { $packagelist = $this->entity->getValueByKey("packages"); echo count($packagelist); } ?></td>
        </tr>
    </tbody>
</table>

<?php if($this->entity->getValueByKey("piwik_id") > 0) :?>
<h2>Seitenbesuche der letzten 30 Tage</h2>
    <img src="<?php echo $this->piwikVisitChart; ?>">
<?php endif; ?>

<h2>Server-Statistik</h2>
<?php if(!$this->entity->getValueByKey("stats")): ?>
    <p>keine Server-Statistik vorhanden</p>
<?php else: ?>
    <table id="statslist" class="table table-striped">
    <thead>
        <tr>
            <th>Tabellenname</th>
            <th>Anzahl</th>
        </tr>
    </thead>
    <tbody>
        <?php $stats = $this->entity->getValueByKey("stats"); ?>
        <?php foreach($stats as $key => $value): ?>        
            <tr>
                <td><?php echo $key; ?></td>
                <td><?php echo $value; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<h2>Plugins</h2>
<?php if ($this->entity->getValueByKey("plugins") == ""): ?>
    <p>keine Plugin-Liste vorhanden</p>
<?php else: ?>
    <?php $pluginlist = $this->entity->getValueByKey("plugins"); ?>
    <table id="pluginlist" class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Anzahl gefundener Installationen</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($pluginlist as $id => $plugin): ?>
                <tr>
                    <td><a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showModuleDetail", "id" => $plugin["id"])); ?>"><?php echo $plugin["name"]; ?></a></td>
                    <td><?php echo $plugin["installs"]; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<h2>Packages</h2>
<?php if ($this->entity->getValueByKey("packages") == ""): ?>
    <p>keine Package-Liste vorhanden</p>
<?php else: ?>
    <?php $packages = $this->entity->getValueByKey("packages"); ?>
    <table id="packagelist" class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Anzahl gefundener Installationen</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($packages as $id => $package): ?>
                <tr>
                    <td><a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showModuleDetail", "id" => $package["id"])); ?>"><?php echo $package["name"]; ?></a></td>
                    <td><?php echo $package["installs"]; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>