<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Portallist</title>

    <!-- Core CSS - Include with every page -->
    <link href="<?php echo $this->mediaUrl; ?>sb_admin2/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $this->mediaUrl; ?>sb_admin2/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Page-Level Plugin CSS - Blank -->

    <!-- SB Admin CSS - Include with every page -->
    <link href="<?php echo $this->mediaUrl; ?>sb_admin2/css/sb-admin.css" rel="stylesheet">
    
    <!-- Core Scripts - Include with every page -->
    <script src="<?php echo $this->mediaUrl; ?>sb_admin2/js/jquery-1.10.2.js"></script>
    <script src="<?php echo $this->mediaUrl; ?>sb_admin2/js/bootstrap.min.js"></script>
    <script src="<?php echo $this->mediaUrl; ?>sb_admin2/js/plugins/metisMenu/jquery.metisMenu.js"></script>

    <!-- Page-Level Plugin Scripts - Blank -->

    <!-- SB Admin Scripts - Include with every page -->
    <script src="<?php echo $this->mediaUrl; ?>sb_admin2/js/sb-admin.js"></script>

</head>

<body>

    <div id="wrapper">

        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">logicworks Portallist</a>
            </div>
            <!-- /.navbar-header -->
        </nav>
        <!-- /.navbar-static-top -->

        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            &nbsp;
                        </div>
                    </li>
                    <li>
                        <a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showList")); ?>">Portals</a>
                        <a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showModulesList")); ?>">Modules</a>
                        <?php if($this->isAdmin): ?>
                            <a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "showMd5CheckForm")); ?>">MD5 Check</a>
                            <a href="<?php echo \LwPortalList\Services\Page::getUrl(array("cmd" => "getSystemInfoFromPortalCollection")); ?>">Scan all portals</a>
                        <?php endif; ?>
                    </li>
                </ul>
                <!-- /#side-menu -->
            </div>
            <!-- /.sidebar-collapse -->
        </nav>
        <!-- /.navbar-static-side -->

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-9"><br>
                    <?php echo $this->content; ?>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    

    <!-- Page-Level Demo Scripts - Blank - Use for reference -->

</body>

</html>
